version: '3.4'

services:
  ignitionDev_gateway:
    image: inductiveautomation/ignition:latest
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8060:8060"
    command: 
      -n ignition-dev-gateway -a 127.0.0.1
    volumes:
      - ignitionDev_data:/usr/local/bin/ignition/data
  
     
  
  ignitionDev_db:
    image: mariadb:10.5.8
    ports:
     - "3307:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ignition
      MYSQL_DATABASE: ignition
    volumes:
      - ignitionDev_db:/var/lib/mysql
volumes: 
  ignitionDev_data: 
  ignitionDev_db: 
